#import "/src/components/typx.typ": h, component, meta
#show: meta.with(title: "Typst Cheatsheet", layout: "default")

#let typx-counter = component("/src/components/counter.ts", "typx-counter")

#let example(code, scope: (:)) = {
  code
  eval(code.text, mode: "markup", scope: scope)
}

#heading(level: 1, outlined: false)[Typst Cheatsheet]
This is a comprehensive cheatsheet covering Typst syntax, models, text, and math, styled for the web.

#set heading(numbering: "1.")
#outline(title: "Table of Contents", depth: 2)
#divider()

= Headings
Typst uses `=` for headings. The number of `=` determines the heading level (H1 to H6).

```typst
= H1
== H2
=== H3
==== H4
===== H5
====== H6
```

#heading(level: 1, outlined: false)[H1]
#heading(level: 2, outlined: false)[H2]
#heading(level: 3, outlined: false)[H3]
#heading(level: 4, outlined: false)[H4]
#heading(level: 5, outlined: false)[H5]
#heading(level: 6, outlined: false)[H6]

#divider()
= Text & Formatting
Typst provides granular control over text styling, including capitalization, decorations, and styling.

#example(```typst
Emphasis: _Italics_ and *Bold*.

Combined: *Bold and _Italic_*.

Raw Text: `print("code")`.

Highlight: #highlight[Highlighted].

Underline: #underline[Underlined].

Overline: #overline[Overlined].

Strikethrough: #strike[Strikethrough].

Subscript/Superscript: H#sub[2]O, E = mc#super[2].

Small Capitals: #smallcaps[Small Caps].

Lowercase: #lower("LOWERCASE").

Uppercase: #upper("uppercase").

Smartquote: "Smart" and 'Quotes'.

Line Break: Text \ breaks here.

Lorem: #lorem(5)
```)

#divider()
= Lists
Typst uses `-` for unordered lists and `+` for ordered lists. Definition lists use `/`. Lists can be nested by indenting.

#example(```typst
- Unordered list
  - Nested item

+ Ordered list
  + Nested ordered

/ Term: Definition
```)

#divider()
= Links
Use `#link("url")[text]` for inline links. Raw URLs are automatically linked.

#example(```typst
#link("https://typst.app")[I'm an inline-style link]

Raw URL: https://typst.app
```)

#divider()
= Images
Use `#figure` wrapping our custom `#h("img")` element to display images with captions. (Note: standard `#image()` is reserved for PDF compilation).

#example(scope: (h: h, component: component), ```typst
#figure(
  h("img", src: "https://picsum.photos/480/300?random=1", alt: "A random image generated by Picsum"),
  caption: [A random image]
)
```)

#divider()
= Tables
The `#table` function creates tables. 

#example(```typst
#table(
  columns: (auto, auto, auto),
  [*Tables*], [*Are*], [*Cool*],
  [Col 1], [Col 2], [Col 3]
)
```)

#divider()
= Blockquotes
Use `#quote(block: true)` to create semantic blockquotes, optionally providing an attribution string.

#example(```typst
#quote(block: true, attribution: "Typst Docs")[
  Typst is a new markup-based typesetting system.
]
```)

#divider()
= Divider
Use `#divider()` for horizontal lines.

#example(```typst
#divider()
```)

= Math Operations
Typst has a powerful native math engine. Surround inline math with `$`, or use it block-level by giving it a dedicated line.

#example(```typst
Inline Equation: $E = m c^2$

Fractions: $(a+b)/c$ or $x/y$

Roots: $sqrt(x)$ or $root(3, x)$

Primes: $f'(x)$ or $f''(x)$

Binomials: $binom(n, k)$

Vectors: $vec(1, 2, 3)$

Matrices: $mat(1, 2; 3, 4)$

Cases: $f(x) = cases(1 "if" x > 0, 0 "else")$

Block Equations:
$ sum_(k=1)^n k = (n(n+1)) / 2 $

Multi-line Block:
$ 
  f(x) = x^2 + 2x + 1 \
       = (x + 1)^2 
$
```)

#divider()
= Math Styling & Layout
Math supports advanced attachments, styling, alignment, and semantic grouping.

#example(```typst
Accents: $hat(x), bar(y), diaer(u), vec(a)$

Under/Over: $underbrace(x + y, z)$ or $overbrace(a, b)$

Attach: $x_1^2$ or $scripts(sum)_1^2$

Left/Right Auto-scaling: $lr(( x / y ))$

Cancel: $cancel(x) / cancel(x) = 1$

Styles: $cal(A), frak(B), bb(C)$

Sizes: $display(x/y) != script(x/y)$

Text Operator: $op("argmax")_x f(x)$

Variants: $epsilon != epsilon.alt$

Stretch: $x stretch(=) y$
```)

#divider()
= Data Loading
Typst can natively read JSON, CSV, TOML, YAML, and XML files, allowing you to generate dynamic documents from structured data.

#example(```typst
#let data = json("/src/assets/data.json")
*Title:* #data.title \
*First Item:* #data.items.at(0).name (#data.items.at(0).type)
```)

#divider()
= Interactive Components
You can use the `#h("script")` hyperscript component to easily attach inline JavaScript to elements for client-side interactivity.

#example(scope: (h: h), ```typst
#let inline-counter(id: "example-counter") = {
  h("button#" + id + ".counter", type: "button")[Count is 0]
  h("script", "
    (function() {
      let count = 0;
      const btn = document.getElementById('" + id + "');
      btn?.addEventListener('click', () => {
        btn.innerHTML = `Count is ${++count}`;
      });
    })();
  ")
}

#inline-counter()
```)

Alternatively, you can load a Web Component using the `component` macro:

#example(scope: (component: component), ```typst
#let typx-counter = component("/src/components/counter.ts", "typx-counter")
#typx-counter(class: "btn counter")[Count is 0]
```)

#divider()
= References & Footnotes
Citations use `@`. Footnotes use `#footnote[]`. Bibliographies are generated automatically from `.bib` files.

#example(```typst
Typst is fast#footnote[Typst is written in Rust].
According to @typst, creating PDFs is easy.

#bibliography("/src/assets/works.bib")
```)
