import { glob } from 'glob';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { join, dirname, basename } from 'path';
import { $ } from 'bun';

/**
 * Extracts the body content from an HTML string.
 */
function extractBodyContent(html: string): string {
  return html.match(/<body[^>]*>(.*?)<\/body>/is)?.[1] ?? html;
}

/**
 * Resolves the layout HTML string for a given document content.
 */
async function getLayoutHtml(layoutsDir: string, content: string): Promise<string> {
  // Support #show: meta.with(..., layout: "layoutName", ...)
  const setDocMatch = content.match(/#show:\s*meta\.with\s*\([^)]*layout\s*:\s*"([^"]+)"[^)]*\)/);
  const layoutName = setDocMatch?.[1] ?? 'default';

  const layoutPath = join(layoutsDir, `${layoutName}.html`);
  
  try {
    return await readFile(layoutPath, 'utf-8');
  } catch (error) {
    console.error(`[ERROR] Layout not found: ${layoutPath}`);
    throw error;
  }
}

/**
 * Determines the output path for a compiled HTML file based on its source path.
 */
function determineOutputPath(file: string): string {
  const name = basename(file, '.typ');
  const dir = dirname(file);
  if (name === 'index') {
    return join(dir === '.' ? '' : dir, 'index.html');
  }
  return join(dir === '.' ? '' : dir, `${name}.html`);
}

/**
 * Processes a single Typst file by compiling it and injecting it into the layout.
 */
async function processTypstFile(file: string, pagesDir: string, layoutsDir: string, tempDir: string): Promise<void> {
  const srcPath = join(pagesDir, file);
  const content = await readFile(srcPath, 'utf-8');
  
  let layoutHtml: string;
  try {
    layoutHtml = await getLayoutHtml(layoutsDir, content);
  } catch {
    return;
  }
  
  const tempSrcPath = join(tempDir, `${file.replace(/[/\\]/g, '_')}.typ`);
  const tempOutPath = join(tempDir, `${file.replace(/[/\\]/g, '_')}.html`);
  console.log(`[INFO] Compiling ${file}...`);

  await writeFile(tempSrcPath, content);
  
  try {
    await $`typst compile --root ${process.cwd()} --format html --features html --input is_html=true ${tempSrcPath} ${tempOutPath}`;
  } catch (error) {
    console.error(`[ERROR] Typst compilation failed for ${file}. Ensure 'typst' is installed and on your PATH.`);
    console.error(error instanceof Error ? error.message : String(error));
    return;
  }
  
  const typstHtml = await readFile(tempOutPath, 'utf-8');
  const bodyContent = extractBodyContent(typstHtml);
  let finalHtml = layoutHtml.replace(/<slot\s*\/?>(<\/slot>)?/, bodyContent);
  
  // Extract the title generated by Typst (if any) and inject it into the layout
  const titleMatch = typstHtml.match(/<title[^>]*>(.*?)<\/title>/is);
  if (titleMatch) {
    const titleContent = titleMatch[1];
    finalHtml = finalHtml.replace(/<title[^>]*>.*?<\/title>/is, `<title>${titleContent}</title>`);
  }
  
  const outRelPath = determineOutputPath(file);
  const finalOutPath = join(process.cwd(), '.typx', outRelPath);
  
  await mkdir(dirname(finalOutPath), { recursive: true });
  await writeFile(finalOutPath, finalHtml);
  
  console.log(`[SUCCESS] Generated ${outRelPath}`);
}

/**
 * Discovers Typst files and orchestrates the Static Site Generation build process.
 */
async function buildSSG(): Promise<void> {
  console.log('[INFO] Starting Typx SSG Build...');
  
  const cwd = process.cwd();
  const pagesDir = join(cwd, 'src/pages');
  const layoutsDir = join(cwd, 'src/layouts');
  const typFiles = await glob('**/*.typ', { cwd: pagesDir });
  
  if (typFiles.length === 0) {
    console.log('[INFO] No .typ files found in src/pages.');
    return;
  }
  
  const tempDir = join(cwd, '.typx', '_temp');
  await mkdir(tempDir, { recursive: true });

  await Promise.all(typFiles.map(file => processTypstFile(file, pagesDir, layoutsDir, tempDir)));
  
  console.log('[SUCCESS] SSG Build Complete!');
}

buildSSG().catch(console.error);
